{% set name = "brightway2_nosolver" %}
{% set original_name = "brightway2" %}
{% set version = "2.4.2" %}
{% set sha256 = "8e741b0e9fe504bc740edad800e17eec9907ed53c181ddab3038801ed8caee80" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ original_name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ original_name[0] }}/{{ original_name }}/{{ original_name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python >=3.9
    - setuptools

  run:
    - asteval >=0.9.22
    - bw2analyzer <0.10.99
    - bw2calc >=1.8.1,<1.99
    - bw2data >=3.6.5,<3.99
    - bw2io >=0.8.8,<0.8.9
    - bw2parameters >=0.6.6
    - numpy >=1.22
    - python >=3.9
    - stats_arrays >=0.6.5

test:
  imports:
    - {{ original_name }}

about:
  home: https://github.com/brightway-lca/brightway2
  license: BSD License
  summary: 'Open source framework for life cycle assessment'
  license_family: BSD
