{% set name = "wurst" %}
{% set version = "0.1.2" %}
{% set sha256 = "7383f4a2d98834365f1765da1253543ed32da84d241bedd73bc134817b049e85" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # build command: conda build -c konstantinstadler -c cmutel -c conda-forge wurst
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - appdirs
    - constructive_geometries
    - country_converter
    - docopt
    - fiona
    - numpy
    - pandas
    - python-json-logger
    - shapely
    - tqdm
    - wrapt


  run:
    - python
    - appdirs
    - constructive_geometries
    - country_converter
    - docopt
    - fiona
    - numpy
    - pandas
    - python-json-logger
    - shapely
    - tqdm
    - wrapt

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/IndEcol/wurst
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Code and metadata for linking life cycle assessment databases to other models'
  license_family: BSD
  doc_url: https://wurst.readthedocs.io/
  dev_url: https://github.com/IndEcol/wurst


