{% set name = "wurst" %}
{% set version = "0.3.2" %}
{% set sha256 = "b74415086bdfa4cede38f47febaa9ce7e7b40ad201bed9f0fbd1517d3e9e3bb2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - appdirs
    - constructive_geometries
    - country_converter
    - docopt
    - fiona
    - numpy
    - pandas
    - python-json-logger
    - shapely
    - toolz
    - tqdm
    - wrapt

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/polca/wurst
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Code and metadata for linking life cycle assessment databases to other models'
  license_family: BSD
  doc_url: https://wurst.readthedocs.io/
  dev_url: https://github.com/polca/wurst


