{% set name = "wurst" %}
{% set version = "0.3" %}
{% set sha256 = "61ebbac2dc070e26fa4ae120f4291fbbb012b93fb0c9a114a4e79ca63ec24907" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  # build command: conda build -c konstantinstadler -c cmutel -c conda-forge wurst
  # build command if errors: conda build -c konstantinstadler -c cmutel -c conda-forge wurst --numpy 1.20 --python 3.9
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - appdirs
    - constructive_geometries
    - country_converter
    - docopt
    - fiona
    - numpy
    - pandas
    - python-json-logger
    - shapely
    - toolz
    - tqdm
    - wrapt

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/polca/wurst
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Code and metadata for linking life cycle assessment databases to other models'
  license_family: BSD
  doc_url: https://wurst.readthedocs.io/
  dev_url: https://github.com/polca/wurst


