{% set name = "bw_aggregation" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bw_aggregation-{{ version }}.tar.gz
  sha256: 82c911f623ad29825e9fd2c917187709c6dad524f6d21b9e9fadd7400875d94e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=68.0
    - pip
  run:
    - python >=3.9
    - bw2calc >=2.0.dev16
    - bw2data >=4.0.dev36
    - bw_graph_tools >=0.3.1
    - bw_processing >=0.9.2
    - fs
    - matrix_utils >=0.4.1
    - numpy

test:
  imports:
    - bw_aggregation
  # commands:
  #   - pip check
  requires:
    - pip

about:
  summary: Use aggregated processes for quicker calculations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cmutel
