{% set name = "bw2io" %}
{% set version = "0.6" %}
{% set sha256 = "f6884e68ca9e157fe18ec69c95f645244714a4fa5013554305c9add7dc7c182c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - bw2calc >=1.7.1
    - bw2data >=3.4
    - lxml
    - numpy
    - psutil
    - pyprind
    - python
    - scipy
    - setuptools
    - stats_arrays >=0.4.2
    - unidecode
    - voluptuous
    - xlrd
    - xlsxwriter

  run:
    - bw2calc >=1.7.1
    - bw2data >=3.4
    - lxml
    - numpy
    - psutil
    - pyprind
    - python
    - scipy
    - stats_arrays >=0.4.2
    - unidecode
    - voluptuous
    - xlrd
    - xlsxwriter

test:
  imports:
    - {{ name }}
    - bw2io.data
    - bw2io.export
    - bw2io.extractors
    - bw2io.importers
    - bw2io.strategies

about:
  home: https://brightwaylca.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Tools for importing and export life cycle inventory databases'
  license_family: BSD
  doc_url: https://docs.brightwaylca.org/
  dev_url: https://bitbucket.org/cmutel/brightway2-io
