{% set name = "bw2io" %}
{% set version = "0.7.11.3" %}
{% set sha256 = "19faac2bba6701952f249b9b33c354cd07f9f3a4c279afb282c5d883b9e8b40f" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - bw2calc >=1.7.5
    - bw2data >=3.5.1
    - astunparse >=1.6.1
    - lxml
    - numpy
    - psutil
    - pyprind
    - python
    - scipy
    - stats_arrays >=0.5
    - unidecode
    - voluptuous
    - xlrd
    - xlsxwriter
    - mrio_common_metadata
    - bw_migrations

test:
  imports:
    - {{ name }}
    - bw2io.data
    - bw2io.export
    - bw2io.extractors
    - bw2io.importers
    - bw2io.strategies

about:
  home: https://brightwaylca.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Tools for importing and export life cycle inventory databases'
  license_family: BSD
  doc_url: https://docs.brightwaylca.org/
  dev_url: https://bitbucket.org/cmutel/brightway2-io
