{% set name = "bw2io" %}
{% set version = "0.6.RC3" %}
{% set sha256 = "63a6c46912a65110485642983ad688fdc7b1c51d43d4b907e7bd6c03a11ec7e1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/11/c2/ad2b8c1e75b129d12e00e4d8833d8e7ada6ea67392d964e83e05d1d19f19/bw2io-0.6rc3.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - bw2calc
    - bw2data
    - lxml
    - numpy
    - psutil
    - pyprind
    - python
    - scipy
    - setuptools
    - stats_arrays
    - unidecode
    - voluptuous
    - xlrd
    - xlsxwriter

  run:
    - bw2calc
    - bw2data
    - lxml
    - numpy
    - psutil
    - pyprind
    - python
    - scipy
    - stats_arrays
    - unidecode
    - voluptuous
    - xlrd
    - xlsxwriter

test:
  imports:
    - {{ name }}
    - bw2io.data
    - bw2io.export
    - bw2io.extractors
    - bw2io.importers
    - bw2io.strategies

about:
  home: https://brightwaylca.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Tools for importing and export life cycle inventory databases'
  license_family: BSD
  doc_url: https://docs.brightwaylca.org/
  dev_url: https://bitbucket.org/cmutel/brightway2-io
