{% set name = "bw2io" %}
{% set version = "0.9.dev28" %}
{% set sha256 = "b65217c1ce5d2fa44e6166cf2ba4edbae812f63a5fd3318eeae17cdfd516a7fe" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python
    - setuptools

  run:
    - bw2calc >=2.0.dev17
    - bw2data >=4.0.dev43
    - bw_migrations
    - bw_processing
    - bw_simapro_csv
    - lxml
    - mrio_common_metadata
    - numpy >=1.24,<2
    - openpyxl
    - pyecospold
    - python >=3.10
    - requests
    - scipy
    - stats_arrays >=0.6.5
    - tqdm
    - unidecode
    - voluptuous
    - xlrd
    - xlsxwriter

test:
  imports:
    - {{ name }}
    - bw2io.data
    - bw2io.export
    - bw2io.extractors
    - bw2io.importers
    - bw2io.strategies

about:
  home: https://brightway.dev/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Tools for importing and export life cycle inventory databases'
  license_family: BSD
  doc_url: https://docs.brightway.dev
  dev_url: https://github.com/brightway-lca/brightway2-io
