{% set name = "bw2io" %}
{% set version = "0.9.dev26" %}
{% set sha256 = "635a2ecca33a4548add4f094c80efb042426d4257a5ecacff6a567c110ad9503" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools

  run:
    - bw2calc >=2.0.dev16
    - bw2data >=4.0.dev32
    - bw_migrations
    - bw_processing
    - lxml
    - mrio_common_metadata
    - numpy >=1.24
    - openpyxl
    - python >=3.10
    - requests
    - scipy
    - stats_arrays >=0.6.5
    - tqdm
    - unidecode
    - voluptuous
    - xlrd
    - xlsxwriter

test:
  imports:
    - {{ name }}
    - bw2io.data
    - bw2io.export
    - bw2io.extractors
    - bw2io.importers
    - bw2io.strategies

about:
  home: https://brightway.dev/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Tools for importing and export life cycle inventory databases'
  license_family: BSD
  doc_url: https://docs.brightway.dev
  dev_url: https://github.com/brightway-lca/brightway2-io
