{% set name = "bentso" %}
{% set version = "0.2.1" %}
{% set sha256 = "83b2763bcbfeeee4faa04de2087a0bfe078ed9222205bae0822ae89f42eda4fc" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - appdirs
    - beautifulsoup4
    - docopt
    - entsoe-py
    - pandas
    - peewee
    - pytest
    - pytest-cov
    - pytz
    - requests

test:
  imports:
    - bentso

about:
  home: https://github.com/BONSAMURAIS/bentso
  license: BSD License
  license_file: LICENSE
  summary: 'BONSAI living model for European electricity via ENTSO-E API'
license_family: BSD
