{% set name = "bw2calc" %}
{% set version = "2.0.dev17" %}
{% set sha256 = "ea55a4f32b3f6815fb5af9bce623f1fc51042c2194d686a3c191d3871fe52a17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python >=3.9
    - setuptools

  run:
    - bw_processing >=0.9.5
    - fsspec
    - json-logging
    - matrix_utils >=0.4.3
    - numpy >=1.20,<2
    - pandas
    - pydantic
    - python >=3.9
    - scipy
    - setuptools
    - stats_arrays

test:
  requires:
    - pytest
    - bw2data >=4.0.dev40

  imports:
    - {{ name }}

about:
  home: https://brightway.dev/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'The calculation engine for the Brightway2 life cycle assessment framework'
  license_family: BSD
  doc_url: https://docs.brightway.dev
  dev_url: https://github.com/brightway-lca/brightway2-calc/
