{% set name = "bw2calc" %}
{% set version = "1.7.1" %}
{% set sha256 = "22de2e0d6120f141373f24312865a278984e4967569b21fa69b282f724db39ae" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - eight
    - numpy
    - scipy
    - stats_arrays

  run:
    - python
    - eight
    - numpy
    - scipy
    - stats_arrays

test:
  imports:
    - {{ name }}

about:
  home: https://brightwaylca.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'The calculation engine for the Brightway2 life cycle assessment framework'
  license_family: BSD
  doc_url: https://docs.brightwaylca.org/
  dev_url: https://bitbucket.org/cmutel/brightway2-calc/
