{% set name = "bw2calc" %}
{% set version = "2.0.dev12" %}
{% set sha256 = "7295a87064f0c6bc175fca937269426dcb96b7673dca45ae2c98336f966d57ad" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python >=3.9
    - setuptools

  run:
    - python
    - setuptools
    - numpy >=1.20
    - scipy
    - stats_arrays
    - bw_processing >=0.8
    - matrix_utils >=0.2.5

test:
  requires:
    - pytest
    - bw2data >=4.0.dev17

  imports:
    - {{ name }}

about:
  home: https://brightway.dev/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'The calculation engine for the Brightway2 life cycle assessment framework'
  license_family: BSD
  doc_url: https://docs.brightway.dev
  dev_url: https://github.com/brightway-lca/brightway2-calc/
