{% set name = "pandarus_remote" %}
{% set version = "1.0" %}
{% set sha256 = "52e8bd053609e792521ce181855b3acaa26af0c7da1009fc0b5f4a6e8e619661" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - appdirs
    - certifi
    - docopt
    - fiona
    - flask
    - numpy
    - pandarus
    - peewee <3
    - pyproj
    - python
    - rasterio
    - rasterstats
    - redis
    - requests
    - rq
    - rtree
    - setuptools
    - shapely

  run:
    - appdirs
    - certifi
    - docopt
    - fiona
    - flask
    - numpy
    - pandarus
    - peewee <3
    - pyproj
    - python
    - rasterio
    - rasterstats
    - redis
    - requests
    - rq
    - rtree
    - shapely

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/cmutel/pandarus_remote
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Pandarus_remote is a web service for processing and managing data for regionalized life cycle assessment using pandarus'
  license_family: BSD
