{% set name = "presamples" %}
{% set version = "0.2.3" %}
{% set sha256 = "91e20f9dcc3abf9d3e98ec11d6d0795b5c9409cc2bdc6fbbd387775594e3fb84" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - astunparse >1.5.0
    - bw2calc >=1.7.3
    - bw2data >=3.4.3
    - bw2parameters >=0.6.6
    - numpy
    - peewee >3.0
    - scipy
    - stats_arrays
    - wrapt

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/PascalLesage/presamples/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Package to write, load, manage and verify numerical arrays, called presamples'
  license_family: BSD
  dev_url: https://github.com/PascalLesage/presamples/
