{% set name = "presamples" %}
{% set version = "0.2.1" %}
{% set sha256 = "7fbbe03ff597afce85fa70e9ff0650b8162f2bdb8d01c9e53001213db3991eb9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - bw2calc >=1.7.1
    - bw2data >=3.4.2
    - bw2parameters >=0.6.4
    - numpy
    - peewee >3.0
    - scipy
    - stats_arrays
    - wrapt
    - python
    - setuptools

  run:
    - bw2calc >=1.7.1
    - bw2data >=3.4.2
    - bw2parameters >=0.6.4
    - numpy
    - peewee >3.0
    - scipy
    - stats_arrays
    - wrapt

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/PascalLesage/brightway2-presamples
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'This is a package for the creation and use of presampled values in Monte Carlo for Brightway LCA framework.'
  license_family: BSD
  dev_url: https://github.com/PascalLesage/brightway2-presamples
