{% set name = "rower" %}
{% set version = "0.3" %}
{% set sha256 = "8d3907486894349f4869404f168e41c39e414a8585f381a3a9091054ab29c8e8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python >=3.9
    - setuptools

  run:
    - appdirs
    - bw2data
    - pyprind
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/cmutel/rower
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Consistently define, label, and manage "Rest-of-World" locations for processes in Brightway databases'
  license_family: BSD
  dev_url: https://github.com/cmutel/rower
