{% set name = "bw2analyzer" %}
{% set version = "0.11.1" %}
{% set sha256 = "b9a85ea4a2b80c3cb02e22e4c7856177a94d3d3b5763ff37a49262063a9dafd0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools

  run:
    - bw2calc >=2.0.dev3
    - bw2data >=4.0.dev8
    - matplotlib-base
    - numpy
    - pandas
    - pyprind
    - python
    - requests
    - scipy
    - stats_arrays
    - tabulate

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/brightway-lca/brightway2-analyzer
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Interpretation and other tools for Brightway2 LCA framework'
  license_family: BSD
