{% set name = "matrix_utils" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/matrix_utils-{{ version }}.tar.gz
  sha256: b3205657f13ba74df7eac34dbf5f814e25e7857a0bd7fc254d2b5b9b9ff98f54

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=68.0
    - pip
  run:
    - python >=3.9
    - numpy <2
    - scipy
    - pandas
    - bw_processing >=0.9.5
    - stats_arrays

test:
  imports:
    - matrix_utils
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Tools to create matrices from data packages
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cmutel
