{% set name = "stats_arrays" %}
{% set version = "0.6.2" %}
{% set sha256 = "d24eff099b227acd2b05dde4ebe8b5ea9babb9c3ebfb85add4ad1571a8672b5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - numpy
    - python
    - scipy

test:
  imports:
    - stats_arrays

about:
  home: http://stats-arrays.readthedocs.io/en/latest/
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'The stats_arrays package provides a standard NumPy array interface for defining uncertain parameters used in models, and classes for Monte Carlo sampling.'
  license_family: BSD
  doc_url: http://stats-arrays.readthedocs.io/en/latest/
  dev_url: https://bitbucket.org/cmutel/stats_arrays
