{% set name = "brightway2" %}
{% set version = "2.2" %}
{% set sha256 = "b2b3e24cea7fb3103ecdf1e9245fdaef2590041deabe837e8e9321a34a689f12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - appdirs
    - asteval
    - bw2analyzer
    - bw2calc
    - bw2data
    - bw2io >=0.5.10
    - bw2parameters
    - docopt
    - eight
    - flask
    - future
    - lxml
    - numpy
    - peewee >3.0
    - psutil
    - pypardiso
    - pyprind
    - python
    - requests
    - scipy
    - setuptools
    - stats_arrays
    - unicodecsv
    - voluptuous
    - whoosh
    - xlrd
    - xlsxwriter

  run:
    - appdirs
    - asteval
    - bw2analyzer
    - bw2calc
    - bw2data
    - bw2io >=0.5.10
    - bw2parameters
    - docopt
    - eight
    - flask
    - future
    - lxml
    - numpy
    - peewee >3.0
    - psutil
    - pypardiso
    - pyprind
    - python
    - requests
    - scipy
    - stats_arrays
    - unicodecsv
    - voluptuous
    - whoosh
    - xlrd
    - xlsxwriter

test:
  imports:
    - {{ name }}

about:
  home: https://bitbucket.org/cmutel/brightway2
  license: BSD License
  summary: 'Open source framework for life cycle assessment'
  license_family: BSD
