{% set name = "brightway2" %}
{% set version = "2.4.1" %}
{% set sha256 = "0f0af59a0f74df6cb0446bb4ff71794712945d93ab51a83aaaaa85ef174b3588" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools

  run:
    - asteval >=0.9.22
    - bw2analyzer <0.10.99
    - bw2calc <1.99
    - bw2data <3.99
    - bw2io <0.8.9
    - bw2parameters >=0.6.6
    - numpy >=1.20
    - "libblas=*=*mkl"
    - pypardiso
    - python
    - stats_arrays >=0.6.5

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/brightway-lca/brightway2
  license: BSD License
  summary: 'Open source framework for life cycle assessment'
  license_family: BSD
