{% set name = "brightway2" %}
{% set version = "2.3" %}
{% set sha256 = "d4a6662bc7e6a41dcee6f8a478a070ba35269c0bd2bcbe59938acf239094e5c6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - appdirs
    - asteval
    - bw2analyzer >=0.9.4
    - bw2calc >=1.7.8
    - bw2data >=3.6.1
    - bw2io >=0.7.11.3
    - bw2parameters >=0.6.6
    - docopt
    - eight
    - flask
    - future
    - lxml
    - numpy
    - peewee >=3.9.4
    - psutil
    - pypardiso
    - pyprind
    - python
    - requests
    - scipy
    - stats_arrays
    - unicodecsv
    - voluptuous
    - whoosh
    - xlrd
    - xlsxwriter
    - mrio_common_metadata
    - bw_migrations

test:
  imports:
    - {{ name }}

about:
  home: https://bitbucket.org/cmutel/brightway2
  license: BSD License
  summary: 'Open source framework for life cycle assessment'
  license_family: BSD
