{% set name = "bw2parameters" %}
{% set version = "0.6.2" %}
{% set sha256 = "8d010b7c13a0b02346612d1927dd8446eb6eebeacfece62a2a232fe49575323a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - asteval
    - astunparse
    - numpy
    - python
    - setuptools
    - stats_arrays

  run:
    - asteval
    - astunparse
    - numpy
    - python
    - stats_arrays

test:
  imports:
    - {{ name }}

about:
  home: https://bitbucket.org/cmutel/brightway2-parameters
  license: BSD 2-Clause
  license_file: LICENSE
  summary: 'Library for storing, validating, and calculating with parameters. Designed to work with the Brightway2 life cycle assessment framework, but is generic enough to work in other use cases.'
  license_family: BSD
  dev_url: https://bitbucket.org/cmutel/brightway2-parameters
