{% set name = "bw2io" %}
{% set version = "1.0.2" %}
{% set sha256 = "1cfdaeb02b5617a05051e0bc372774a76d3a265462a5d8186c5e6c4308403626" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - appdirs
    - fiona
    - numpy
    - pyproj
    - rtree
    - rasterio
    - rasterstats
    - shapely
    - certifi

  run:
    - python
    - appdirs
    - fiona
    - numpy
    - pyproj
    - rtree
    - rasterio
    - rasterstats
    - shapely
    - certifi

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/cmutel/pandarus
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'GIS toolkit for regionalized life cycle assessment'
  license_family: BSD
  doc_url: http://pandarus.readthedocs.io/
