{% set name = "bw2data" %}
{% set version = "3.4" %}
{% set sha256 = "3b2208e126f2eea7bba7cca918570e672a1814a3c9380a1163e2ad3317992550" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - appdirs
    - bw2parameters
    - docopt
    - eight
    - fasteners
    - future
    - lxml
    - numpy
    - peewee
    - psutil
    - pyprind
    - python
    - requests
    - scipy
    - setuptools
    - stats_arrays
    - unicodecsv
    - voluptuous
    - whoosh
    - wrapt

  run:
    - appdirs
    - bw2parameters
    - docopt
    - eight
    - fasteners
    - future
    - lxml
    - numpy
    - peewee
    - psutil
    - pyprind
    - python
    - requests
    - scipy
    - stats_arrays
    - unicodecsv
    - voluptuous
    - whoosh
    - wrapt

test:
  imports:
    - {{ name }}

about:
  home: https://brightwaylca.org/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Data management for the Brightway2 life cycle assessment framework'
  license_family: BSD
  doc_url: https://docs.brightwaylca.org/
  dev_url: https://bitbucket.org/cmutel/brightway2-data/
