{% set name = "bw2data" %}
{% set version = "3.6.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bw2data-{{ version }}.tar.gz
  sha256: 3ce1f7b9242f0daa7762e4f98588af3acd5b921530713957a1edabbfd2579453

build:
  entry_points:
    - bw2-uptodate = bw2data.bin.bw2_uptodate:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - pip
  run:
    - python
    - appdirs
    - bw2parameters
    - docopt
    - eight
    - fasteners
    - future
    - lxml
    - numpy
    - peewee >=3.9.4
    - psutil
    - pyprind
    - requests >=1.1.0
    - scipy
    - stats_arrays
    - unicodecsv
    - voluptuous
    - whoosh
    - wrapt

test:
  imports:
    - bw2data
  commands:
    - pip check
    - bw2-uptodate --help
  requires:
    - pip

about:
  home: https://bitbucket.org/cmutel/brightway2-data
  summary: Tools for the management of inventory databases and impact assessment methods. Part of the Brightway2 LCA Framework
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cmutel
