{% set name = "bw2data" %}
{% set version = "4.0.dev38" %}
{% set sha256 = "cf3f12220887f3314798965e263f0ea2b51922468ed95af6446cb80e20e76629" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python >=3.9
    - setuptools

  run:
    - bw2parameters >=0.6.6
    - bw_processing >=0.9.2
    - docopt >=0.6.2
    - lxml >=4.6
    - numpy <2
    - peewee
    - platformdirs
    - python >=3.9
    - scipy >=1.6
    - stats_arrays
    - tqdm
    - voluptuous >=0.12
    - whoosh
    - wrapt >=1.12

test:
  imports:
    - {{ name }}

about:
  home: https://brightway.dev/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Data management for the Brightway v2.5 life cycle assessment framework'
  license_family: BSD
  doc_url: https://docs.brightway.dev
  dev_url: https://github.com/brightway-lca/brightway2-data/
