{% set name = "bw2data" %}
{% set version = "4.0.dev42" %}
{% set sha256 = "7d839ef40f5d540a3c36ea3ce7cd742cd308facd2bf0568082ef1cf7ab108d2a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python >=3.9
    - setuptools

  run:
    - bw2parameters >=0.6.6
    - bw_processing >=0.9.5
    - fsspec
    - lxml >=4.6
    - numpy >=1.20,<2
    - peewee >=3.14.4
    - platformdirs
    - pydantic-settings
    - python >=3.9
    - rapidfuzz
    - scipy >=1.6
    - stats_arrays >=0.6.5
    - tqdm
    - voluptuous >=0.12
    - whoosh
    - wrapt >=1.12

test:
  imports:
    - {{ name }}

about:
  home: https://brightway.dev/
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: 'Data management for the Brightway v2.5 life cycle assessment framework'
  license_family: BSD
  doc_url: https://docs.brightway.dev
  dev_url: https://github.com/brightway-lca/brightway2-data/
