{% set name = "bw_processing" %}
{% set version = "0.8" %}
{% set sha256 = "f35d1e610390c4a0bf425a708dc2140be30cbbb85523da56f606e1edfa5cd567" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  # Conda-forge conda build pins a specific python ABI to help distinguish
  # cpython from pypy. This *shouldn't* apply to noarch packages, but...
  # Suggestion from https://github.com/conda/conda-build/issues/3956#issuecomment-631800846
  # to block this inclusion. Ugly but seems to work.
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - python
    - setuptools

  run:
    - numpy
    - python
    - pandas
    - fs

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/brightway-lca/bw_processing
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Tools to create structured arrays in a common format'
  license_family: BSD
  doc_url: https://3.docs.brightwaylca.org/
  dev_url: https://github.com/brightway-lca/bw_processing
