{% set name = "bw_processing" %}
{% set version = "0.1.1" %}
{% set sha256 = "2ef0f156aea6c754aaa57c959e3369f606c737993f70efad1762e3f90ac58a93" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - numpy
    - python

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/brightway-lca/bw_processing
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Tools to create structured arrays in a common format'
  license_family: BSD
  doc_url: https://3.docs.brightwaylca.org/
  dev_url: https://github.com/brightway-lca/bw_processing
