{% set name = "perdu" %}
{% set version = "0.1.1" %}
{% set sha256 = "2a53a2dae0fa76f3750e4a0a418674f01f421b5481be2c66b6d5a4216843a507" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - appdirs
    - docopt
    - flask
    - peewee
    - python
    - rdflib
    - rdflib-jsonld
    - whoosh

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/cmutel/perdu
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python library and webapp for searching standard industry and product classifiers'
  license_family: BSD
