{% set name = "perdu" %}
{% set version = "0.2" %}
{% set sha256 = "9106e8f6097e6b6e450c0da5e43e930c952fb596bb7dc44723f9c270f891a0b8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - appdirs
    - docopt
    - flask
    - pandas
    - peewee
    - python
    - rdflib
    - rdflib-jsonld
    - whoosh
    - xlrd

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/cmutel/perdu
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Python library and webapp for searching standard industry and product classifiers'
  license_family: BSD
