{% set name = "constructive_geometries" %}
{% set version = "0.5" %}
{% set sha256 = "c7a99f96717ef2f56b3ce79c591e1983fd9c1ff5fd322e7ce8d25e2674d8f14e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - fiona
    - setuptools
    - shapely
    - wrapt

  run:
    - python
    - fiona
    - shapely
    - wrapt

test:
  # Python imports
  imports:
    - constructive_geometries

about:
  home: https://bitbucket.org/cmutel/py-constructive-geometries
  license: BSD License
  summary: 'Tool to build new geometrical definitions from the ecoinvent topology'
  license_family: BSD
