{% set name = "constructive_geometries" %}
{% set version = "0.6.1" %}
{% set sha256 = "76c33bbc2494ba1e473dcb533b6b711ff3273abb18fc4d7bdb66684ca2a9319b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - country_converter
    - fiona
    - python
    - setuptools
    - shapely
    - wrapt

  run:
    - country_converter
    - fiona
    - python
    - shapely
    - wrapt

test:
  imports:
    - {{ name }}

about:
  home: https://github.com/cmutel/constructive_geometries
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Simple tools to define world locations from a set of topological faces and set algebra'
  license_family: BSD
