package:
  name: bw2regional
  version: "0.4.2"

source:
  fn: bw2regional-0.4.2.tar.gz
  url: https://pypi.python.org/packages/36/26/27fabceb44175c4427ea756efee9aff9e8d8b214721bd039c9bad3e2dcbf/bw2regional-0.4.2.tar.gz
  md5: 6e26c018c88fefa5c6393a70d5f6e913

build:
  noarch_python: True

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - brightway2
    - bw2calc >=1.2
    - bw2data >=2.0
    - constructive_geometries
    - eight
    - fiona
    - pandas
    - pandarus >=1.0
    - requests
    - stats_arrays
    - voluptuous
    - wrapt

  run:
    - python
    - brightway2
    - bw2calc >=1.2
    - bw2data >=2.0
    - constructive_geometries
    - eight
    - fiona
    - pandas
    - pandarus >=1.0
    - requests
    - stats_arrays
    - voluptuous
    - wrapt

test:
  # Python imports
  # imports:
  #   - bw2regional
  #   - bw2regional.lca

about:
  home: https://bitbucket.org/cmutel/brightway2-regional
  license: BSD License
  summary: ''
  license_family: BSD
